// apps/explorer/frontend/src/components/lenses/LensHealthStrip.tsx
interface Metric { label: string; value: string; sub?: string }

export function LensHealthStrip({ metrics }: { metrics: Metric[] }) {
  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3 mb-8">
      {metrics.map((m) => (
        <div key={m.label} className="bg-vellum-raised border border-quartz rounded-md px-4 py-3">
          <p className="text-[10px] uppercase tracking-[0.1em] text-ink-muted font-medium">{m.label}</p>
          <p className="text-2xl font-semibold text-ink-primary mt-1 tabular-nums">{m.value}</p>
          {m.sub && <p className="text-[11px] text-ink-muted mt-0.5 tabular-nums">{m.sub}</p>}
        </div>
      ))}
    </div>
  );
}

// src/vault_frontend/src/lib/components/explorer/LensHealthStrip.svelte
<script lang="ts">
  export interface HealthMetric {
    label: string;
    value: string;
    sub?: string;
    tone?: 'normal' | 'good' | 'caution' | 'danger' | 'muted';
  }

  interface Props {
    title: string;
    metrics: HealthMetric[];
    loading?: boolean;
  }
  let { title, metrics, loading = false }: Props = $props();

  const toneClass: Record<NonNullable<HealthMetric['tone']>, string> = {
    normal: '',
    good: 'text-teal-400',
    caution: 'text-amber-400',
    danger: 'text-pink-400',
    muted: 'text-gray-500',
  };
</script>

<div class="explorer-card">
  <div class="text-[11px] uppercase tracking-[0.14em] font-medium mb-3" style="color: var(--rumi-text-secondary);">
    {title}
  </div>
  {#if loading}
    <div class="flex items-center py-1">
      <div class="w-4 h-4 border-2 border-gray-600 border-t-teal-400 rounded-full animate-spin"></div>
    </div>
  {:else}
    <div class="flex flex-wrap items-baseline gap-x-8 gap-y-3">
      {#each metrics as m}
        <div class="flex flex-col min-w-0">
          <span class="text-xs text-gray-500">{m.label}</span>
          <span class="text-base font-semibold tabular-nums mt-0.5 {toneClass[m.tone ?? 'normal']}">
            {m.value}
          </span>
          {#if m.sub}
            <span class="text-[11px] text-gray-500 mt-0.5">{m.sub}</span>
          {/if}
        </div>
      {/each}
    </div>
  {/if}
</div>
